Bugfix speed improvements
EmicoEcommerce/Magento2TweakwiseExport pull request #31
Opened 2024-02-28 15:15 UTC by ah-net

This pull request brings about a 20% improvement in export speed for production sites(based on my very limited dataset).

It addresses two main issues:

1) Previously, `$this->log->debug` was invoked for every category/product to log a message in the debug log, without checking if the site is in production mode. This incurred unnecessary overhead as the function is slow and doesn't log anything in production mode. The fix involves adding a check for production mode before invoking the function.

2) Price fields were fetched for each row within the `getPriceValue` function. However, since the price fields are already known, they are now passed to the function instead of being fetched again for every price.

2024-03-01 13:29 UTC, jansentjeu requested changes

2024-03-01 13:29 UTC, jansentjeu commented on Model/Write/Products.php
> +                if ($this->enableLog) {
When was a value set for `enableLog`?

2024-03-01 13:29 UTC, jansentjeu commented on Model/Write/Products.php
> +        EavConfig $eavConfig,
Remove

2024-03-01 13:29 UTC, jansentjeu commented on Model/Write/Products.php
> +    protected $enableLog;
Once used but never set?

2024-03-01 13:29 UTC, jansentjeu commented on Model/Write/Products/CollectionDecorator/Price.php
> +    protected function getPriceValue(int $storeId, array $priceData, array $priceFields): float
`$storeId` is not used anymore now. It can be removed from the parameters and PHPdoc. Also add the `$priceFields` param to PHPdoc

2024-03-01 13:29 UTC, jansentjeu commented on Model/Helper.php
Why not adding the production mode logic to `Model/Logger.php`? Then we don't need the `if ($this->helper->enableLog)` statements.

For example in `Model/Logger.php`:

    public function debug($message, array $context = [], bool $enableOnProductionMode = true): void
    {
        if(!$enableOnProductionMode && $this->state->getMode() === State::MODE_PRODUCTION) {
            return;
        }
        
        $this->log->debug('[TweakWise] ' . $message, $context);
    }
Then we can just call: `$this->log->debug(sprintf('Skip price for store %s (disabled)', $store->getName()), [], false)`

Or if you never want to enable debug logs on production mode:

    public function debug($message, array $context = []): void
    {
        if($this->state->getMode() === State::MODE_PRODUCTION) {
            return;
        }

        $this->log->debug('[TweakWise] ' . $message, $context);
    }

Then we don't need to change the `$this->log->debug()` calls.

Or set an `debugLogIsEnabled` variable in `Model/Logger.php`:

    public function debug($message, array $context = []): void
    {
        if($this->debugLogIsEnabled) {
            return;
        }

        $this->log->debug('[TweakWise] ' . $message, $context);
    }

2024-03-05 10:15 UTC, ah-net commented on Model/Helper.php
Function moved to logger

2024-03-05 10:15 UTC, ah-net commented on Model/Write/Products/CollectionDecorator/Price.php
> +    protected function getPriceValue(int $storeId, array $priceData, array $priceFields): float
Changes implemented

2024-03-05 10:16 UTC, ah-net commented on Model/Write/Products.php
> +    protected $enableLog;
Code removed

2024-03-05 10:16 UTC, ah-net commented on Model/Write/Products.php
> +        EavConfig $eavConfig,
Code removed

2024-03-05 10:16 UTC, ah-net commented on Model/Write/Products.php
> +                if ($this->enableLog) {
Code removed

2024-03-05 10:16 UTC, ah-net commented on Model/Write/Products.php
> +    protected $enableLog;
Code removed

2024-03-05 20:30 UTC, bramstroker commented on Model/Logger.php
> +        }
```suggestion
        $this->enableDebugLog = ($state->getMode() === State::MODE_PRODUCTION);
```

2024-03-12 09:50 UTC, merged